name: PDF-Writer
version: 0.03
abstract: PDF writer abstraction layer
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
